spring:
  application:
    name: AUTENTICACAO-SERVICE
  profiles:
    active: dev

eureka:
  instance:
    prefer-ip-address: true
    hostname: autenticacao-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://registry:8761/eureka/
server:
  port: 8081