spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/admin_db}
    username: ${SPRING_DATASOURCE_USERNAME:admin_user}
    password: ${SPRING_DATASOURCE_PASSWORD:admin_pass}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    url: ${SPRING_FLYWAY_URL:jdbc:postgresql://localhost:5434/admin_db}
    user: ${SPRING_FLYWAY_USER:admin_user}
    password: ${SPRING_FLYWAY_PASSWORD:admin_pass}
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_FORMAT_SQL:true}
        jdbc:
          time_zone: ${SPRING_JPA_TIMEZONE:UTC}
    open-in-view: false

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
