auth:
  jwt:
    # use o MESMO secret base64 do autenticacao-servico
    secret: ${AUTH_JWT_SECRET_BASE64:kKm5G2MIj9aMOK/y6v0tXpLHmv8nciqTmrLb+HlJk3k=}
    expiration: 28800

spring:
  application:
    name: CATALOGO-SERVICE
  profiles:
    active: dev
  rsocket:
    server:
      port: 8082
  security:
    oauth2:
      resourceserver:       # <<<< sem espaço!
        jwt: {}             # não defina string aqui; usaremos JwtDecoder via @Bean
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    open-in-view: false

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
