services:
  postgres:
    image: postgres:15
    container_name: admin-postgres-1
    environment:
      POSTGRES_DB: admin_db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin_pass
      TZ: UTC
      PGTZ: UTC
    ports:
      - "5433:5432"        # publica o container na porta 5433 do host
    volumes:
      - pgdata:/var/lib/postgresql/data  # volume nomeado (mais f√°cil de resetar)

volumes:
  pgdata:
